using Bogus;
using Bogus.DataSets;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.ContentModel;
using System.ComponentModel.Design;
using System.Net;
using System.Numerics;
using System.Runtime.Intrinsics.Arm;
using System.Security.Policy;
using System;
using System.Threading;
using System.Threading.Tasks;
using UltraWebsite.Models.Entity;

namespace UltraWebsite.Models.Configurations
{
    public class CatagoryConfigration : IEntityTypeConfiguration<Catagory>
    {
        public int index { get; set; }




        public void Configure(EntityTypeBuilder<Catagory> builder)
        {
            index = 1;
            builder.HasData(new Catagory { Id = index++, Name = "Kitab"                                   });
builder.HasData(new Catagory { Id = index++, Name = "            Kadin                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "            Giyim                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elbise                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tisört                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gömlek                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kot Pantolon                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kot Ceket                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Pantolon                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mont                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bluz                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ceket                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Etek                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kazak                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tesettür                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Büyük Beden                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ayakkabi                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Topuklu Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sneaker                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Babet                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sandalet                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bot                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Aksesuar & amp; Çanta                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çanta                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Taki                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sapka                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cüzdan                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Iç Giyim                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Pijama Takimi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gecelik                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sütyen                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Iç Çamasiri Takimlari                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Fantezi Giyim                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çorap                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks & amp; Designer                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Çanta                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Giyim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tasarim Giyim                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tasarim Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kozmetik                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Parfüm                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Göz Makyaji                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cilt Bakim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Bakimi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Makyaj                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Agiz Bakim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cinsel Saglik                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Vücut Bakim                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hijyenik Ped                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dus Jeli &amp; Kremleri              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Epilasyon Ürünleri                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ruj                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günes Kremi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor & amp; Outdoor                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sweatshirt                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tisört                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Sütyeni                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tayt                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Esofman                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kosu Ayakkabisi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ekipmanlari                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kar Botu                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Ekipmanlari                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Besinleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Aksesuarlari                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Erkek                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Giyim                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tisört                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sort                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gömlek                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Esofman                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Pantolon                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ceket                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kot Pantolon                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yelek                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kazak                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mont                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Takim Elbise                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sweatshirt                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Forma                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ayakkabi                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yürüyüs Ayakkabisi                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Krampon                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sneaker                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Klasik                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bot                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kisisel Bakim                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Parfüm                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cinsel Saglik                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tiras Sonrasi Ürünler                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tiras Biçagi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat & amp; Aksesuar                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günes Gözlügü                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cüzdan                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kemer                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çanta                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sapka                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bileklik                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Iç Giyim                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Boxer                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çorap                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Pijama                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Atlet                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor & amp; Outdoor                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Esofman                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "T - shirt                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sweatshirt                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Forma                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Çorap                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Giyim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Bot                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ekipmanlari                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Ekipmanlari                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Besinleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Aksesuarlari                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elektronik                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tiras Makinesi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cep Telefonu                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akilli Saat                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akilli Bileklik                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Laptop                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyun & amp; Konsollar                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elektrikli Bisiklet                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "E - pin ve Cüzdan Kodu               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks & amp; Designer                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Giyim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Çanta                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Anne & amp; Çocuk                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Takimlari                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ayakkabi                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hastane Çikisi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yenidogan Kiyafetleri                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tulum & amp; Salopet                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Body & amp; Zibin                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tisört & amp; Atlet                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elbise                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sort                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Patigi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Bezi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Mamasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Islak Mendil                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kiz Çocuk                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elbise                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sweatshirt                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Esofman                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Iç Giyim &amp; Pijama                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tisört & amp; Atlet                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tayt                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sort                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mont                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çocuk Oyun Evi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncak Bebek                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncak Mutfak                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Erkek Çocuk                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sweatshirt                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Esofman                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Iç Giyim & amp; Pijama               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tisört & amp; Atlet                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Okul Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sort                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gömlek                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mont                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncak Traktör                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akülü Araba                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kumandali Araba                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Bakim                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Banyo & amp; Tuvalet                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Sampuani                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Krem & amp; Yaglar                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Çantasi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncak                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Egitici Oyuncaklar                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncak Araba                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncak Bebek                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek & amp; Okul Öncesi             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kumandali Oyuncak                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Robot Oyuncak                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyun Hamuru                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tasima & amp; Güvenlik               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Arabasi & amp; Puset           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "            Park Yatak               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ana Kucagi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Portbebe & amp; Kanguru              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yürüteç                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oto Koltugu                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Beslenme Emzirme                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Biberon & amp; Emzik                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gögüs Pompasi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mama Sandalyesi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mama Önlügü                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Alistirma Bardagi                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ev & amp; Mobilya                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sofra & amp; Mutfak                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yemek Takimi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çatal Kasik Biçak Seti               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Baharat Takimi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bardak                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Firin & amp; Kek Kalibi              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çaydanlik                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tencere Seti                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Banyo                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Havlu & amp; Havlu Seti              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bornoz                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Banyo Seti                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "            Banyo Paspasi            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ev Tekstili                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yatak Odasi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hali & amp; Kilim & amp; Paspas      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Perde                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Nevresim Takimi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yastik                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kirlent ve Kilifi                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ev Dekorasyon                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dekoratif Aksesuar                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tablo                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Duvar Saati                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ayna                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Trendyol Sanat                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Aydinlatma                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Avize                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lambader                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Abajur                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Mobilya                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Salon & amp; Oturma Odasi            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yatak Odasi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bahçe Mobilyasi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çalisma Odasi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ev Gereçleri                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Düzenleyici                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çamasirlik                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sepet & amp; Saklama Kutusu          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hobi                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kitap                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Puzzle                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Boya & amp; Resim                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kutu Oyunlari                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kirtasiye & amp; Ofis                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Defter                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kalem                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor & amp; Outdoor                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kosu Bandi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dumbell & amp; Agirlik               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Pilates & amp; Yoga                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Eliptik Bisiklet                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Otomobil & amp; Motosiklet           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oto Aksesuar                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oto Paspasi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oto Lastik                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kask                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yapi Market                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Banyo Yapi Malzemeleri               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elektrikli El Aleti                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hirdavat Ürünleri                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Boya                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Matkap                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ampul                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Süpermarket                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ev & amp; Temizlik                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çamasir Yikama                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bulasik Yikama                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ev Temizlik                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Paspas & amp; Mop                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kagit Ürünleri                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gida                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çay                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kahve                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kuruyemis                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kahvaltilik                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Organik Ürünler                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Diyabetik Ürünler                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kisisel Bakim                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Bakimi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Agda & amp; Epilasyon                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Banyo & amp; Dus                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Agiz Bakim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cilt Bakimi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Vücut Bakimi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saglik & amp; Spor                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cinsel Saglik                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hijyenik Ped                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Besinleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Vitamin & amp; Ek Gida               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hasta Bezi &amp; Temizlik            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Petshop                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kedi Mamasi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kedi Kumu                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Köpek Mamasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Köpek Tasmasi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kus Ürünleri                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akvaryum Ürünleri                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Bakim                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Süt Arttirici Içecekler              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Ek Besin                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Bezi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Islak Mendil &amp; Havlu             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bebek Kozmetik                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kozmetik                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Makyaj                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Göz Makyaji                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ten Makyaji                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dudak Makyaji                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Makyaj Seti                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oje & amp; Aseton                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Fondöten                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Parfüm & amp; Deodorant              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Parfüm                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Parfüm Setleri                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Deodorant & amp; Roll - on           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Vücut Spreyi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cilt Bakimi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yüz Kremi                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yüz Temizleme                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yüz Maskesi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Göz Bakimi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günes Koruyucu                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cilt Serumu                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "El & amp; Ayak Bakimi                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Bakimi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sampuan                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Sekillendirici                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Serumu & amp; Maskesi            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Boyasi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Epilasyon & amp; Tiras               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tüy Dökücü                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Agda                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tiras Biçagi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Epilatör                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tiras Köpügü                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Genel Bakim                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cinsel Saglik                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hijyenik Ped                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Vücut Bakimi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "El ve Ayak Bakimi                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dus Jeli ve Kremi                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bakim Yaglari                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ayakkabi & amp; Çanta                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kadin Ayakkabi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Topuklu Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bot & amp; Bootie                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "            Sandalet                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Terlik                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kadin Çanta                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Omuz Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sirt Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cüzdan                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bel Çantasi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Erkek Ayakkabi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Klasik Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bot                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sneaker                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kosu Ayakkabisi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Krampon                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Erkek Çanta                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sirt Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Postaci Çantasi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cüzdan & amp; Kartlik                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çocuk Ayakkabi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günlük Ayakkabi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Babet                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çocuk Çanta                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sirt Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Okul Çantasi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks & amp; Designer                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Çanta                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Lüks Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tasarim Çanta                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tasarim Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat & amp; Aksesuar                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kadin                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günes Gözlügü                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Taki                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cüzdan                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kemer                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sapka                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Atki Bere Eldiven                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sal & amp; Fular                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Semsiye                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gözlük Kabi                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Aksesuari                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hasir Bilezik                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Burma Bilezik                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "22 Ayar Bilezik                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Taki & amp; Mücevher                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kolye                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Küpe                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bileklik                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Halhal                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yüzük                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Altin                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Piercing                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elektronik Aksesuarlar               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Telefon Kilifi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akilli Saat                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akilli Bileklik                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Erkek                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günes Gözlügü                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cüzdan & amp; Kartlik                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kemer                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bileklik                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sapka Bere Eldiven                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kravat                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Valiz                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çocuk Aksesuar                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saat                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Günes Gözlügü                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sapka                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elektronik                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Küçük Ev Aletleri                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Süpürge                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ütü                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Robot Süpürge                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kahve Makinesi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Blender                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çay Makinesi                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tost Makinesi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Waffle Makinesi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tarti                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Giyilebilir Teknoloji                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akilli Saat                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Akilli Bileklik                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Telefon                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Cep Telefonu                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kapak & amp; Kilif                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sarj Cihazlari                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Powerbank                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bilgisayar & amp; Tablet             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Laptop                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tablet                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bilgisayar Bilesenleri               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Monitör                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yazici & amp; Tarayici               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çevre Birimleri                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ag & amp; Modem                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "TV & amp; Görüntü & amp; Ses         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Televizyon                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Soundbar                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Projeksiyon Cihazi                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Media Player                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hoparlör                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kulaklik                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kisisel Bakim Aletleri               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Düzlestirici                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tiras Makinesi                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Masasi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Saç Kurutma Makinesi                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Epilasyon Aleti                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Beyaz Esya                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Buzdolabi                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çamasir Makinesi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bulasik Makinesi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Ankastre                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Derin Dondurucu                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Klima                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kombi                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Elektronik Aksesuarlar               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bilgisayar Aksesuar                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Telefon Aksesuarlari                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "TV Aksesuarlari                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Veri Depolama                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyunculara Özel                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Playstation                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Xbox                                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Nintendo                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Playstation Oyunlari                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Konsol Aksesuarlari                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncu Bilgisayari                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncu Donanimlari                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Oyuncu Monitörleri                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Foto & amp; Kamera                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Aksiyon Kamera                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Fotograf Makinesi                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dijital Kod & amp; Ürünler           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor & amp; Outdoor                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Giyim                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Tisört                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Sort                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Tayt                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Sütyeni                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Esofman                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Sweatshirt                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yagmurluk                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Yelek                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Atlet                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Forma                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Mont                            "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Sapka                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çorap                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Ayakkabi                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sneaker                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kosu Ayakkabisi                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Hali Saha Ayakkabisi                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Basketbol Ayakkabisi                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yürüyüs Ayakkabisi                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Ayakkabi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tenis Ayakkabisi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Voleybol Ayakkabisi                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Fitness Ayakkabisi                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Deniz Ayakkabisi                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kaykay Ayakkabisi                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Outdoor Bot                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Terlik                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Spor Malzemeleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Deniz & amp; Plaj                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kaykay                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Paten                                "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kamp Malzemeleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dagcilik & amp; Tirmanis             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Aksiyon Kamera                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Çadir Uyku Tulumu                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Su Sporu Malzemeleri                 "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dalis Malzemeleri                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Balikçilik Malzemeleri               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Tenis Malzemeleri                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kayak ve Snowboard                   "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Okçuluk                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Bisiklet                             "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sehir Bisikleti                      "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dag Bisikleti                        "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Fitness Kondisyon                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Pilates Malzemeleri                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Fitness Aletleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kondisyon Bisikleti                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kosu Bandi                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Yoga Malzemeleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Dambil Seti                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Agirlik Plakalari                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Barfiks                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Sporcu Besinleri                     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Protein Tozu                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Amino Asit                           "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Karbonhidrat                         "                                   });
builder.HasData(new Catagory { Id = index++, Name = "L - Karnitin(CLA)                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Güç ve Performans                    "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Gida Takviyesi & amp; Vitaminler     "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Kreatin                              "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Protein Bar                          "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Shaker                               "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Top                                  "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Basketbol Topu                       "                                   });
builder.HasData(new Catagory { Id = index++, Name = "Futbol Topu                          " });
        }
        public List<Product> list { get; set; }
       
    }
}
