// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltraWebsite.Data;

#nullable disable

namespace UltraWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UltraWebsite.Models.Entity.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catalogues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitab"
                        },
                        new
                        {
                            Id = 2,
                            Name = "  Süpürge                                "
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ütü                                      "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Robot Süpürge                            "
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kahve Makinesi                           "
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blender                                  "
                        },
                        new
                        {
                            Id = 7,
                            Name = "Çay Makinesi                             "
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tost Makinesi                            "
                        },
                        new
                        {
                            Id = 9,
                            Name = "Waffle Makinesi                          "
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tartı                                    "
                        },
                        new
                        {
                            Id = 11,
                            Name = "Giyilebilir Teknoloji                    "
                        },
                        new
                        {
                            Id = 12,
                            Name = "Akıllı Saat                              "
                        },
                        new
                        {
                            Id = 13,
                            Name = "Akıllı Bileklik                          "
                        },
                        new
                        {
                            Id = 14,
                            Name = "Telefon                                  "
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cep Telefonu                             "
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kapak & Kılıf                            "
                        },
                        new
                        {
                            Id = 17,
                            Name = "Şarj Cihazları                           "
                        },
                        new
                        {
                            Id = 18,
                            Name = "Powerbank                                "
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bilgisayar & Tablet                      "
                        },
                        new
                        {
                            Id = 20,
                            Name = "Laptop                                   "
                        },
                        new
                        {
                            Id = 21,
                            Name = "Tablet                                   "
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bilgisayar Bileşenleri                   "
                        },
                        new
                        {
                            Id = 23,
                            Name = "Monitör                                  "
                        },
                        new
                        {
                            Id = 24,
                            Name = "Yazıcı & Tarayıcı                        "
                        },
                        new
                        {
                            Id = 25,
                            Name = "Çevre Birimleri                          "
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ağ & Modem                               "
                        },
                        new
                        {
                            Id = 27,
                            Name = "TV & Görüntü & Ses                       "
                        },
                        new
                        {
                            Id = 28,
                            Name = "Televizyon                               "
                        },
                        new
                        {
                            Id = 29,
                            Name = "Soundbar                                 "
                        },
                        new
                        {
                            Id = 30,
                            Name = "Projeksiyon Cihazı                       "
                        },
                        new
                        {
                            Id = 31,
                            Name = "Media Player                             "
                        },
                        new
                        {
                            Id = 32,
                            Name = "Hoparlör                                 "
                        },
                        new
                        {
                            Id = 33,
                            Name = "Kulaklık                                 "
                        },
                        new
                        {
                            Id = 34,
                            Name = "Kişisel Bakım Aletleri                   "
                        },
                        new
                        {
                            Id = 35,
                            Name = "Saç Düzleştirici                         "
                        },
                        new
                        {
                            Id = 36,
                            Name = "Tıraş Makinesi                           "
                        },
                        new
                        {
                            Id = 37,
                            Name = "Saç Maşası                               "
                        },
                        new
                        {
                            Id = 38,
                            Name = "Saç Kurutma Makinesi                     "
                        },
                        new
                        {
                            Id = 39,
                            Name = "Epilasyon Aleti                          "
                        },
                        new
                        {
                            Id = 40,
                            Name = "Beyaz Eşya                               "
                        },
                        new
                        {
                            Id = 41,
                            Name = "Buzdolabı                                "
                        },
                        new
                        {
                            Id = 42,
                            Name = "Çamaşır Makinesi                         "
                        },
                        new
                        {
                            Id = 43,
                            Name = "Bulaşık Makinesi                         "
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ankastre                                 "
                        },
                        new
                        {
                            Id = 45,
                            Name = "Derin Dondurucu                          "
                        },
                        new
                        {
                            Id = 46,
                            Name = "Klima                                    "
                        },
                        new
                        {
                            Id = 47,
                            Name = "Kombi                                    "
                        },
                        new
                        {
                            Id = 48,
                            Name = "Elektronik Aksesuarlar                   "
                        },
                        new
                        {
                            Id = 49,
                            Name = "Bilgisayar Aksesuar                      "
                        },
                        new
                        {
                            Id = 50,
                            Name = "Telefon Aksesuarları                     "
                        },
                        new
                        {
                            Id = 51,
                            Name = "TV Aksesuarları                          "
                        },
                        new
                        {
                            Id = 52,
                            Name = "Veri Depolama                            "
                        },
                        new
                        {
                            Id = 53,
                            Name = "Oyunculara Özel                          "
                        },
                        new
                        {
                            Id = 54,
                            Name = "Playstation                              "
                        },
                        new
                        {
                            Id = 55,
                            Name = "Xbox                                     "
                        },
                        new
                        {
                            Id = 56,
                            Name = "Nintendo                                 "
                        },
                        new
                        {
                            Id = 57,
                            Name = "Playstation Oyunları                     "
                        },
                        new
                        {
                            Id = 58,
                            Name = "Konsol Aksesuarları                      "
                        },
                        new
                        {
                            Id = 59,
                            Name = "Oyuncu Bilgisayarı                       "
                        },
                        new
                        {
                            Id = 60,
                            Name = "Oyuncu Donanımları                       "
                        },
                        new
                        {
                            Id = 61,
                            Name = "Oyuncu Monitörleri                       "
                        },
                        new
                        {
                            Id = 62,
                            Name = "Foto & Kamera                            "
                        },
                        new
                        {
                            Id = 63,
                            Name = "Aksiyon Kamera                           "
                        });
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductAdjective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("catalogue_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("catalogue_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.Product", b =>
                {
                    b.HasOne("UltraWebsite.Models.Entity.Catagory", "Catalogue")
                        .WithMany("Products")
                        .HasForeignKey("catalogue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogue");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.ProductTag", b =>
                {
                    b.HasOne("UltraWebsite.Models.Entity.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltraWebsite.Models.Entity.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.Catagory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.Product", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("UltraWebsite.Models.Entity.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
